<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generatorMetamodels" nsURI="http://www.example.org/generatorMetamodels"
    nsPrefix="generatorMetamodels">
  <eClassifiers xsi:type="ecore:EClass" name="MultipleChoice" eSuperTypes="#//ResponseModality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbChoices" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultVerification" eSuperTypes="#//SubObjective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkIsRight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetOfFacts" eSuperTypes="#//AbstractFact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="facts" lowerBound="1" upperBound="-1"
        eType="#//AbstractFact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProblemResolution" eSuperTypes="#//SubObjective"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExitRoom" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleCompletion" eSuperTypes="#//SubObjective"/>
  <eClassifiers xsi:type="ecore:EClass" name="CurrentProgression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningobjective" lowerBound="1"
        eType="#//LearningObjective"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" lowerBound="1" eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dungeon">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//GameMode"
        defaultValueLiteral="LINEAR"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" lowerBound="1" eType="#//EntryRoom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Settings" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//ResponseModality"/>
  <eClassifiers xsi:type="ecore:EClass" name="QuestionRoom" abstract="true" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="LearningPath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningobjectives" upperBound="-1"
        eType="#//LearningObjective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subobjectives" upperBound="-1"
        eType="#//SubObjective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge" eType="#//Knowledge"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFact" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleQuestionRoom" eSuperTypes="#//QuestionRoom"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fact" eSuperTypes="#//AbstractFact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LearnerPlayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningprofile" lowerBound="1"
        eType="#//LearningProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameprofile" lowerBound="1"
        eType="#//GameProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HighLevelActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" lowerBound="1" eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntryRoom" eSuperTypes="#//Room"/>
  <eClassifiers xsi:type="ecore:EClass" name="Door"/>
  <eClassifiers xsi:type="ecore:EClass" name="BossRoom" eSuperTypes="#//QuestionRoom"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reconstruction" eSuperTypes="#//SubObjective"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubObjective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfApparition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfValidFacts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbConsecutiveSuccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsemodality" lowerBound="1"
        eType="#//ResponseModality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" upperBound="-1"
        eType="#//Settings" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseModality" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleCompletion" eSuperTypes="#//SubObjective"/>
  <eClassifiers xsi:type="ecore:EClass" name="GameProfile"/>
  <eClassifiers xsi:type="ecore:EClass" name="LearningProfile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningpath" lowerBound="1"
        eType="#//LearningPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentprogressions" upperBound="-1"
        eType="#//CurrentProgression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LearningObjective">
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" upperBound="-1"
        eType="#//Level" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prerequisites" upperBound="-1"
        eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setoffacts" upperBound="-1"
        eType="#//SetOfFacts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GameMode">
    <eLiterals name="LINEAR" literal="LINEAR"/>
    <eLiterals name="LABIRINTHINE" value="1"/>
    <eLiterals name="RAMDOM" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subobjectives" upperBound="-1"
        eType="#//SubObjective"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" upperBound="-1"
        eType="#//Settings" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Knowledge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgefacts" upperBound="-1"
        eType="#//AbstractFact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactValidityVerification" eSuperTypes="#//SubObjective"/>
  <eClassifiers xsi:type="ecore:EClass" name="Room" abstract="true"/>
</ecore:EPackage>
