#

pluginName = GeneratorMetamodels Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_MultipleChoice_type = Multiple Choice
_UI_ResultVerification_type = Result Verification
_UI_SetOfFacts_type = Set Of Facts
_UI_ProblemResolution_type = Problem Resolution
_UI_ExitRoom_type = Exit Room
_UI_MultipleCompletion_type = Multiple Completion
_UI_CurrentProgression_type = Current Progression
_UI_Dungeon_type = Dungeon
_UI_Settings_type = Settings
_UI_Input_type = Input
_UI_QuestionRoom_type = Question Room
_UI_LearningPath_type = Learning Path
_UI_AbstractFact_type = Abstract Fact
_UI_SimpleQuestionRoom_type = Simple Question Room
_UI_Fact_type = Fact
_UI_LearnerPlayer_type = Learner Player
_UI_HighLevelActivity_type = High Level Activity
_UI_EntryRoom_type = Entry Room
_UI_Door_type = Door
_UI_BossRoom_type = Boss Room
_UI_Reconstruction_type = Reconstruction
_UI_SubObjective_type = Sub Objective
_UI_ResponseModality_type = Response Modality
_UI_SimpleCompletion_type = Simple Completion
_UI_GameProfile_type = Game Profile
_UI_LearningProfile_type = Learning Profile
_UI_LearningObjective_type = Learning Objective
_UI_Level_type = Level
_UI_Knowledge_type = Knowledge
_UI_FactValidityVerification_type = Fact Validity Verification
_UI_Room_type = Room
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_MultipleChoice_nbChoices_feature = Nb Choices
_UI_ResultVerification_checkIsRight_feature = Check Is Right
_UI_SetOfFacts_facts_feature = Facts
_UI_SetOfFacts_name_feature = Name
_UI_CurrentProgression_learningobjective_feature = Learningobjective
_UI_CurrentProgression_level_feature = Level
_UI_Dungeon_mode_feature = Mode
_UI_Dungeon_rooms_feature = Rooms
_UI_Dungeon_entry_feature = Entry
_UI_LearningPath_learningobjectives_feature = Learningobjectives
_UI_LearningPath_subobjectives_feature = Subobjectives
_UI_LearningPath_knowlege_feature = Knowlege
_UI_LearningPath_name_feature = Name
_UI_Fact_description_feature = Description
_UI_LearnerPlayer_learningprofile_feature = Learningprofile
_UI_LearnerPlayer_gameprofile_feature = Gameprofile
_UI_HighLevelActivity_level_feature = Level
_UI_SubObjective_name_feature = Name
_UI_SubObjective_percentageOfApparition_feature = Percentage Of Apparition
_UI_SubObjective_percentageOfValidFacts_feature = Percentage Of Valid Facts
_UI_SubObjective_nbConsecutiveSuccess_feature = Nb Consecutive Success
_UI_SubObjective_responsemodality_feature = Responsemodality
_UI_SubObjective_settings_feature = Settings
_UI_ResponseModality_responseTime_feature = Response Time
_UI_LearningProfile_learningpath_feature = Learningpath
_UI_LearningProfile_currentprogressions_feature = Currentprogressions
_UI_LearningObjective_levels_feature = Levels
_UI_LearningObjective_prerequisites_feature = Prerequisites
_UI_LearningObjective_setoffacts_feature = Setoffacts
_UI_LearningObjective_ID_feature = ID
_UI_LearningObjective_name_feature = Name
_UI_Level_subobjectives_feature = Subobjectives
_UI_Level_ID_feature = ID
_UI_Level_settings_feature = Settings
_UI_Knowledge_name_feature = Name
_UI_Knowledge_setoffacts_feature = Setoffacts
_UI_Unknown_feature = Unspecified

_UI_GameMode_LINEAR_literal = LINEAR
_UI_GameMode_LABIRINTHINE_literal = LABIRINTHINE
_UI_GameMode_RAMDOM_literal = RAMDOM
_UI_LearningPath_knowledge_feature = Knowledge
_UI_LearnerPlayer_firstname_feature = Firstname
_UI_LearnerPlayer_lastname_feature = Lastname
_UI_Knowledge_knowledgefacts_feature = Knowledgefacts
