<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generator" nsURI="http://www.example.org/generator" nsPrefix="generator">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFact" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetOfFacts" eSuperTypes="#//AbstractFact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="facts" lowerBound="1" upperBound="-1"
        eType="#//AbstractFact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fact" eSuperTypes="#//AbstractFact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Knowledge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgefacts" upperBound="-1"
        eType="#//AbstractFact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GPBricks">
    <eLiterals name="SELECT"/>
    <eLiterals name="MOVE" value="1"/>
    <eLiterals name="AVOID" value="2"/>
    <eLiterals name="DESTROY" value="3"/>
    <eLiterals name="MANAGE" value="4"/>
    <eLiterals name="WRITE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dungeon">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" lowerBound="1" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//DungeonMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" lowerBound="1" eType="#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" lowerBound="1" eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningobjective" lowerBound="1"
        eType="#//LearningObjective"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomaccess" upperBound="-1"
        eType="#//RoomAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomtype" lowerBound="1"
        eType="#//RoomType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" eType="#//Question"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" eType="#//Elements"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameplays" eType="#//Gameplays"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementtypes" eType="#//ElementTypes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abilities" upperBound="-1"
        eType="#//Abilities" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomtypes" eType="#//RoomTypes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomType" abstract="true">
    <eOperations name="getDirections" upperBound="-1" eType="#//Directions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positions" upperBound="-1"
        eType="#//Position" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmallRoomType" eSuperTypes="#//RoomType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directions" lowerBound="1"
        upperBound="4" eType="#//Directions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LargeRoomType" eSuperTypes="#//RoomType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directions" lowerBound="1"
        upperBound="8" eType="#//Directions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Directions">
    <eLiterals name="SOUTH"/>
    <eLiterals name="EAST" value="1"/>
    <eLiterals name="NORTH" value="2"/>
    <eLiterals name="WEST" value="3"/>
    <eLiterals name="SOUTH_EAST" value="4"/>
    <eLiterals name="SOUTH_WEST" value="5"/>
    <eLiterals name="NORTH_EAST" value="6"/>
    <eLiterals name="NORTH_WEST" value="7"/>
    <eLiterals name="EAST_SOUTH" value="8"/>
    <eLiterals name="EAST_NORTH" value="9"/>
    <eLiterals name="WEST_NORTH" value="10"/>
    <eLiterals name="WEST_SOUTH" value="11"/>
    <eLiterals name="NONE" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomAccess">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Directions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherroomaccess" eType="#//RoomAccess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRooms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//DungeonMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DungeonMode">
    <eLiterals name="LINEAR"/>
    <eLiterals name="LABYRINTHINE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasktype" lowerBound="1"
        eType="#//TaskType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfApparition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbConsecutiveSuccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfValidFacts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LearningDomain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningpaths" upperBound="-1"
        eType="#//LearningPath" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasktypes" eType="#//TaskTypes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsemodalities" eType="#//ResponseModalities"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LearningPath">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningobjective" upperBound="-1"
        eType="#//LearningObjective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge" lowerBound="1"
        eType="#//Knowledge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LearningObjective">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prerequisites" upperBound="-1"
        eType="#//Prerequisite" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" upperBound="-1"
        eType="#//Level" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setoffacts" lowerBound="1"
        upperBound="-1" eType="#//SetOfFacts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Prerequisite">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="succesPercentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredLevel" lowerBound="1"
        eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VerifiableElement">
    <eLiterals name="FULL_FACTS"/>
    <eLiterals name="RESULTS" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTLevel" eSuperTypes="#//Level">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildSetup" eType="#//TableBuild"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultPositionSetup" eType="#//ResultPosition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minInterval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxInterval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TableBuild">
    <eLiterals name="TABLE_OPERAND"/>
    <eLiterals name="OPERAND_TABLE" value="1"/>
    <eLiterals name="MIX" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResultPosition">
    <eLiterals name="RIGHT" value="1"/>
    <eLiterals name="LEFT"/>
    <eLiterals name="MIX" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TargetElement">
    <eLiterals name="RESULT"/>
    <eLiterals name="TABLE" value="1"/>
    <eLiterals name="OPERAND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MTCompletionType" eSuperTypes="#//CompletionType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targets" lowerBound="1"
        upperBound="-1" eType="#//TargetElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskTypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasktypes" upperBound="-1"
        eType="#//TaskType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Order">
    <eLiterals name="ASCENDING"/>
    <eLiterals name="DESCENDING" value="1"/>
    <eLiterals name="MIX" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompletionType" eSuperTypes="#//TaskType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbMissingElements" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factOrder" eType="#//Order"
        defaultValueLiteral="MIX"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="naturalLanguage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerificationType" abstract="true" eSuperTypes="#//TaskType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verifyTrue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReconstructionType" eSuperTypes="#//TaskType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbFalseProposition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsemodalities" upperBound="2"
        eType="#//ResponseModality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactVerificationType" eSuperTypes="#//VerificationType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultVerificationType" eSuperTypes="#//VerificationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbFalseProposition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerationContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gamecontext" lowerBound="1"
        eType="#//GameContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="learnerplayer" lowerBound="1"
        eType="#//LearnerPlayer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LearnerPlayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="progression" eType="#//Progression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningpath" lowerBound="1"
        eType="#//LearningPath"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Progression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentobjectivelevels"
        upperBound="-1" eType="#//CurrentObjectiveLevel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CurrentObjectiveLevel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="learningobjective" lowerBound="1"
        eType="#//LearningObjective"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="achieved" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" lowerBound="1" eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1"
        eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incompleteFact" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseModality" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleChoice" eSuperTypes="#//ResponseModality">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbChoices" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnterResponse" eSuperTypes="#//ResponseModality"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionEType" eSuperTypes="#//ElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abilities" upperBound="-1"
        eType="#//Ability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EPassiveAbility">
    <eLiterals name="DETECT"/>
    <eLiterals name="KILL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EActiveAbility">
    <eLiterals name="PORTABLE"/>
    <eLiterals name="PUSHABLE" value="1"/>
    <eLiterals name="KILLABLE" value="3"/>
    <eLiterals name="BREAKABLE" value="3"/>
    <eLiterals name="PULLABLE" value="4"/>
    <eLiterals name="NONE" value="5"/>
    <eLiterals name="OPENABLE" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ability" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActiveAbility" eSuperTypes="#//Ability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ability" eType="#//EActiveAbility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassiveAbility" eSuperTypes="#//Ability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ability" eType="#//EPassiveAbility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gameplay">
    <eOperations name="isAvailable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gamerules" lowerBound="1"
        upperBound="-1" eType="#//GameRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" eType="#//AvatarEquipment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//GPBricks"
        defaultValueLiteral="MOVE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ability2activate" eType="#//EActiveAbility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interactionelementtype"
        eType="#//InteractionEType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuyableElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bought" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ElementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AvatarEquipment" eSuperTypes="#//BuyableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Elements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gameplays">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameplays" lowerBound="1"
        upperBound="-1" eType="#//Gameplay" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementTypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementtypes" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abilities">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abilities" upperBound="-1"
        eType="#//Ability" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoomTypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomtypes" lowerBound="1"
        upperBound="-1" eType="#//RoomType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquipmentEType" eSuperTypes="#//ElementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementPosition" eSuperTypes="#//Position">
    <eStructuralFeatures xsi:type="ecore:EReference" name="autorizedETypes" upperBound="-1"
        eType="#//InteractionEType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compliancerelations" upperBound="-1"
        eType="#//ComplianceRelations" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modality2RoomType" eSuperTypes="#//ComplianceRelations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsemodality" lowerBound="1"
        eType="#//ResponseModality"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomtype" lowerBound="1"
        upperBound="-1" eType="#//RoomType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplianceRelations" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaskType2Gameplay" eSuperTypes="#//ComplianceRelations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameplay" lowerBound="1"
        upperBound="-1" eType="#//Gameplay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasktype" lowerBound="1"
        eType="#//TaskType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseModalities">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsemodalities" upperBound="-1"
        eType="#//ResponseModality" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gameplay2RoomType" eSuperTypes="#//ComplianceRelations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomtype" lowerBound="1"
        eType="#//RoomType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameplay" lowerBound="1"
        upperBound="-1" eType="#//Gameplay"/>
  </eClassifiers>
</ecore:EPackage>
