/**
 */
package generatorMetamodels.provider;

import generatorMetamodels.util.GeneratorMetamodelsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class GeneratorMetamodelsItemProviderAdapterFactory extends GeneratorMetamodelsAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GeneratorMetamodelsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.MultipleChoice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultipleChoiceItemProvider multipleChoiceItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.MultipleChoice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultipleChoiceAdapter() {
		if (multipleChoiceItemProvider == null) {
			multipleChoiceItemProvider = new MultipleChoiceItemProvider(this);
		}

		return multipleChoiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.ResultVerification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultVerificationItemProvider resultVerificationItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.ResultVerification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultVerificationAdapter() {
		if (resultVerificationItemProvider == null) {
			resultVerificationItemProvider = new ResultVerificationItemProvider(this);
		}

		return resultVerificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.SetOfFacts} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetOfFactsItemProvider setOfFactsItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.SetOfFacts}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetOfFactsAdapter() {
		if (setOfFactsItemProvider == null) {
			setOfFactsItemProvider = new SetOfFactsItemProvider(this);
		}

		return setOfFactsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.ProblemResolution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProblemResolutionItemProvider problemResolutionItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.ProblemResolution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProblemResolutionAdapter() {
		if (problemResolutionItemProvider == null) {
			problemResolutionItemProvider = new ProblemResolutionItemProvider(this);
		}

		return problemResolutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.ExitRoom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExitRoomItemProvider exitRoomItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.ExitRoom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExitRoomAdapter() {
		if (exitRoomItemProvider == null) {
			exitRoomItemProvider = new ExitRoomItemProvider(this);
		}

		return exitRoomItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.MultipleCompletion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultipleCompletionItemProvider multipleCompletionItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.MultipleCompletion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultipleCompletionAdapter() {
		if (multipleCompletionItemProvider == null) {
			multipleCompletionItemProvider = new MultipleCompletionItemProvider(this);
		}

		return multipleCompletionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.CurrentProgression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CurrentProgressionItemProvider currentProgressionItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.CurrentProgression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCurrentProgressionAdapter() {
		if (currentProgressionItemProvider == null) {
			currentProgressionItemProvider = new CurrentProgressionItemProvider(this);
		}

		return currentProgressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.Dungeon} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DungeonItemProvider dungeonItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.Dungeon}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDungeonAdapter() {
		if (dungeonItemProvider == null) {
			dungeonItemProvider = new DungeonItemProvider(this);
		}

		return dungeonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.Input} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputItemProvider inputItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.Input}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputAdapter() {
		if (inputItemProvider == null) {
			inputItemProvider = new InputItemProvider(this);
		}

		return inputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.LearningPath} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LearningPathItemProvider learningPathItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.LearningPath}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLearningPathAdapter() {
		if (learningPathItemProvider == null) {
			learningPathItemProvider = new LearningPathItemProvider(this);
		}

		return learningPathItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.SimpleQuestionRoom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimpleQuestionRoomItemProvider simpleQuestionRoomItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.SimpleQuestionRoom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSimpleQuestionRoomAdapter() {
		if (simpleQuestionRoomItemProvider == null) {
			simpleQuestionRoomItemProvider = new SimpleQuestionRoomItemProvider(this);
		}

		return simpleQuestionRoomItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.Fact} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FactItemProvider factItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.Fact}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFactAdapter() {
		if (factItemProvider == null) {
			factItemProvider = new FactItemProvider(this);
		}

		return factItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.LearnerPlayer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LearnerPlayerItemProvider learnerPlayerItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.LearnerPlayer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLearnerPlayerAdapter() {
		if (learnerPlayerItemProvider == null) {
			learnerPlayerItemProvider = new LearnerPlayerItemProvider(this);
		}

		return learnerPlayerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.HighLevelActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HighLevelActivityItemProvider highLevelActivityItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.HighLevelActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHighLevelActivityAdapter() {
		if (highLevelActivityItemProvider == null) {
			highLevelActivityItemProvider = new HighLevelActivityItemProvider(this);
		}

		return highLevelActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.EntryRoom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntryRoomItemProvider entryRoomItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.EntryRoom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntryRoomAdapter() {
		if (entryRoomItemProvider == null) {
			entryRoomItemProvider = new EntryRoomItemProvider(this);
		}

		return entryRoomItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.Door} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DoorItemProvider doorItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.Door}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDoorAdapter() {
		if (doorItemProvider == null) {
			doorItemProvider = new DoorItemProvider(this);
		}

		return doorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.BossRoom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BossRoomItemProvider bossRoomItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.BossRoom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBossRoomAdapter() {
		if (bossRoomItemProvider == null) {
			bossRoomItemProvider = new BossRoomItemProvider(this);
		}

		return bossRoomItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.Reconstruction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReconstructionItemProvider reconstructionItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.Reconstruction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReconstructionAdapter() {
		if (reconstructionItemProvider == null) {
			reconstructionItemProvider = new ReconstructionItemProvider(this);
		}

		return reconstructionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.SubObjective} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubObjectiveItemProvider subObjectiveItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.SubObjective}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubObjectiveAdapter() {
		if (subObjectiveItemProvider == null) {
			subObjectiveItemProvider = new SubObjectiveItemProvider(this);
		}

		return subObjectiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.SimpleCompletion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimpleCompletionItemProvider simpleCompletionItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.SimpleCompletion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSimpleCompletionAdapter() {
		if (simpleCompletionItemProvider == null) {
			simpleCompletionItemProvider = new SimpleCompletionItemProvider(this);
		}

		return simpleCompletionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.GameProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GameProfileItemProvider gameProfileItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.GameProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGameProfileAdapter() {
		if (gameProfileItemProvider == null) {
			gameProfileItemProvider = new GameProfileItemProvider(this);
		}

		return gameProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.LearningProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LearningProfileItemProvider learningProfileItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.LearningProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLearningProfileAdapter() {
		if (learningProfileItemProvider == null) {
			learningProfileItemProvider = new LearningProfileItemProvider(this);
		}

		return learningProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.LearningObjective} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LearningObjectiveItemProvider learningObjectiveItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.LearningObjective}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLearningObjectiveAdapter() {
		if (learningObjectiveItemProvider == null) {
			learningObjectiveItemProvider = new LearningObjectiveItemProvider(this);
		}

		return learningObjectiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.Level} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LevelItemProvider levelItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.Level}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLevelAdapter() {
		if (levelItemProvider == null) {
			levelItemProvider = new LevelItemProvider(this);
		}

		return levelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.Knowledge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KnowledgeItemProvider knowledgeItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.Knowledge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKnowledgeAdapter() {
		if (knowledgeItemProvider == null) {
			knowledgeItemProvider = new KnowledgeItemProvider(this);
		}

		return knowledgeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link generatorMetamodels.FactValidityVerification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FactValidityVerificationItemProvider factValidityVerificationItemProvider;

	/**
	 * This creates an adapter for a {@link generatorMetamodels.FactValidityVerification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFactValidityVerificationAdapter() {
		if (factValidityVerificationItemProvider == null) {
			factValidityVerificationItemProvider = new FactValidityVerificationItemProvider(this);
		}

		return factValidityVerificationItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (multipleChoiceItemProvider != null)
			multipleChoiceItemProvider.dispose();
		if (resultVerificationItemProvider != null)
			resultVerificationItemProvider.dispose();
		if (setOfFactsItemProvider != null)
			setOfFactsItemProvider.dispose();
		if (problemResolutionItemProvider != null)
			problemResolutionItemProvider.dispose();
		if (exitRoomItemProvider != null)
			exitRoomItemProvider.dispose();
		if (multipleCompletionItemProvider != null)
			multipleCompletionItemProvider.dispose();
		if (currentProgressionItemProvider != null)
			currentProgressionItemProvider.dispose();
		if (dungeonItemProvider != null)
			dungeonItemProvider.dispose();
		if (inputItemProvider != null)
			inputItemProvider.dispose();
		if (learningPathItemProvider != null)
			learningPathItemProvider.dispose();
		if (simpleQuestionRoomItemProvider != null)
			simpleQuestionRoomItemProvider.dispose();
		if (factItemProvider != null)
			factItemProvider.dispose();
		if (learnerPlayerItemProvider != null)
			learnerPlayerItemProvider.dispose();
		if (highLevelActivityItemProvider != null)
			highLevelActivityItemProvider.dispose();
		if (entryRoomItemProvider != null)
			entryRoomItemProvider.dispose();
		if (doorItemProvider != null)
			doorItemProvider.dispose();
		if (bossRoomItemProvider != null)
			bossRoomItemProvider.dispose();
		if (reconstructionItemProvider != null)
			reconstructionItemProvider.dispose();
		if (subObjectiveItemProvider != null)
			subObjectiveItemProvider.dispose();
		if (simpleCompletionItemProvider != null)
			simpleCompletionItemProvider.dispose();
		if (gameProfileItemProvider != null)
			gameProfileItemProvider.dispose();
		if (learningProfileItemProvider != null)
			learningProfileItemProvider.dispose();
		if (learningObjectiveItemProvider != null)
			learningObjectiveItemProvider.dispose();
		if (levelItemProvider != null)
			levelItemProvider.dispose();
		if (knowledgeItemProvider != null)
			knowledgeItemProvider.dispose();
		if (factValidityVerificationItemProvider != null)
			factValidityVerificationItemProvider.dispose();
	}

}
